### ISSUE TITLE
Method String>>asInteger not present any more

### ISSUE THREAD

**Issue by mmontone** [Cuis-Smalltalk/OSProcess#1]
Seems that `String>>asInteger` is not present in current Cuis anymore, and OSProcess uses it in various places.

I've replaced the call in `isNonUnixMac` method by `findPositiveInteger` in order to make OSProcess load, but I haven't looked at the rest of places.

**Comment by dtlewis290** [comment]
I just pushed an update that includes a fix for this problem. It should be working again now.
