### ISSUE TITLE
Possible to obtain the output of a command?

### ISSUE THREAD

**Issue by mmontone** [Cuis-Smalltalk/OSProcess#3]
Hi,

I would like to obtain a command output (what is written to stdout).

I'm trying like this, but doesn't work: 

res _ OSProcess waitForCommand: 'mycommand'.
res initialStdOut contents.

Is it possible?

**Comment by dtlewis290** [comment]
This requires CommandShell, which is a companion package that works with OSProcess.  CommandShell is only partially ported to Cuis but you can use the early version from https://github.com/dtlewis290/Cuis-Smalltalk-CommandShell.

When both OSProcess and CommandShell are loaded, you can do "OSProcess outputOf: 'mycommand' " to get the output of a command. HTH.

**Comment by mmontone** [comment]
Ah. Thanks.
